services:
  fb:
    image: filebrowser/filebrowser:v2.32.0
    container_name: filebrowser
    restart: unless-stopped
    volumes:
       - ${HOME}:/srv
       - ${HOME}/fb-data/filebrowser.db:/database.db
       - ${HOME}/fb-data/.filebrowser.json:/.filebrowser.json
    user: "${UID}:${GID}"
    ports:
      - 127.0.0.1:8081:80
