name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-tailscale:
    name: Test Tailscale connectivity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci

      - name: Test Tailscale connectivity
        run: |
          tailscale ping --verbose --timeout 10s --c 5 --until-direct=false dev-m1sk9-s1

  test-compose:
    name: Test compose files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testing compose files
        run: |
          for dir in $(find . -name 'compose.yaml' -exec dirname {} \;)
          do
              echo "Testing docker compose in $dir"
              cd $dir
              touch .env
              docker compose config
              cd -
          done
